### ISSUE TITLE
dapps.vm.synced_folder in windows?

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [jesuscript/vagrant-eth-env#1]
Hi, what paths should I set here?
    dapps: /vagrant => D:/eth/env
    dapps: D:\eth\env.vagrant\DAPPS => C:/Users/v/DAPPS
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that
the guest additions are properly installed in the guest and
can work properly. The command attempted was:

**Comment by jesuscript** [comment]
I removed the whole synced folder thing, all together, so closing this
